# This is a basic workflow to help you get started with Actions

name: Build the project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          apt install build-essential curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ccache
          add-apt-repository ppa:ubuntu-toolchain-r/test
          apt install gcc-10 g++-10
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 900 --slave /usr/bin/g++ g++ /usr/bin/g++-10

      - name: Set up the cross compiler
        run: |
          chmod +x ./crosscompiler.sh
          ./crosscompiler.sh

      - name: Build
        run: ./build.sh
        
